sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lmuSBX9ip7kdF7PToBiZelNqlZAm+nJjmId/qsIvIOpDQ1PMxLSOMwc3/Vof1JuZoQmZ9Guy/xo+l5WxMSO/s70US5fm8Xzo1jdMD91Jfb5nPhW6OBYM8I5yLxgQpRlFelqU2+TJBmQVRoMF+ERfMNOO92koZa0GXbUNpBiD0XHi0JTVxJ7Zn2L8XGwq1Jy4Y1Wq/ypntxYecfs9X7+sw0DZ+ZaLuBfTIo0ZzwcqX0jf5/h7SpkVwFo9krf5ba7F/Eej6gYwEFuDeeEk+NGAmsguXND/9rAuHzc3ThbSOkEiIiVPYN44T+1xh/pAWBRb2Omo5YD2tvBrLidjIQsiah7WIPzAmzFS9y89aw2/KcYN66xCFUKZaNdWidIjNYmgNEiM9lwmcJthcUJEkQYWGwBcGPN4RAxKJXnHzyvEtWdytAOZcknqtmiVurEzoRh05FVJtXOTF1tKP1Ahz8CEPnw5S+x1KFHTOaLMVp9MRtJ6l/+reYbw7NkN5kehjhycyx6YO8anA+HoyF46D1ySP7AbHFPtLoALkTFf6YrvKlGsWu6pc/gJe+xq8so0RTft8YkB9h+tVOisdZnJenW1g75bXlDHenhicqlGw0hVWcEhj1MXXOA/9jA8t2Gc6yNCuhLXVilB9e40Qi5kyJsTExH4ig4UGFLm7A5MsLvbYNM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Grand-Babylon-H-tel_2813
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy